# 389. Find the Difference
# Easy
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Return the letter that was added to t.

def find_the_difference(s, t)
  fs = freq(s)
  ft = freq(t)

  ft.each do |k, v|
    return k if v != fs[k]
  end
end

def freq(s)
  f = Hash.new(0)
  s.each_char do |c|
    f[c] += 1
  end
  f
end
