site_name: Craig's Leetcode Solutions
site_url: https://craigpastro.github.io/leetcode/
repo_url: https://github.com/craigpastro/leetcode
site_author: Craig Pastro
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.superfences
theme:
    name: material
    locale: en
plugins:
  - search
  - awesome-pages
